
name = "curl"
version = "0.0.3"

[dependencies]
lang_utils_static = { git = "StanzaOrg/slm_lang_utils", version = "0.0.4" }

[dependencies.libcurl]
pkg="libcurl"
version="8.6.0"
type="conan"
options.fPIC = "True"
options.shared = "False"
options.with_brotli = "False"
options.with_c_ares = "False"
options.with_ca_bundle = "auto"
options.with_ca_fallback = "False"
options.with_ca_path = "auto"
options.with_cookies = "True"
options.with_crypto_auth = "True"
options.with_dict = "True"
options.with_docs = "False"
options.with_file = "True"
options.with_ftp = "True"
options.with_gopher = "True"
options.with_http = "True"
options.with_imap = "True"
options.with_ipv6 = "True"
options.with_largemaxwritesize = "False"
options.with_ldap = "False"
options.with_libgsasl = "False"
options.with_libidn = "False"
options.with_libpsl = "False"
options.with_librtmp = "False"
options.with_libssh2 = "False"
options.with_mqtt = "True"
options.with_nghttp2 = "False"
options.with_ntlm = "True"
options.with_ntlm_wb = "True"
options.with_pop3 = "True"
options.with_proxy = "True"
options.with_rtsp = "True"
options.with_smb = "True"
options.with_smtp = "True"
options.with_ssl = "openssl"
options.with_symbol_hiding = "False"
options.with_telnet = "True"
options.with_tftp = "True"
options.with_threaded_resolver = "True"
options.with_unix_sockets = "True"
options.with_verbose_debug = "True"
options.with_verbose_strings = "True"
options.with_zlib = "True"
options.with_zstd = "False"
